version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: memcached_server_1
      APP_PORT: 
    
  server:
    image: memcached:latest
    command:
      - --conn-limit=1024
      - --memory-limit=64
      - --threads=4



   