services:
  app_proxy:
    environment:
      APP_HOST: pf-influxdb_server_1  # Stelle sicher, dass dieser Name korrekt ist
      APP_PORT: 8086
    depends_on:
      - server

  server:
    image: influxdb:1.11.8
    container_name: pf-influxdb_server_1
    volumes:
      - ${APP_DATA_DIR}/data:/var/lib/influxdb
      - ${APP_DATA_DIR}/config:/etc/influxdb
    ports:
      - "8086:8086"