version: "3.7"

services:

  app_proxy:
    environment: 
    # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: pf-influxdb_server_1
      APP_PORT: 8086
    
  server:
    image: objectscale/influxdb:latest
    volumes:
    - ${APP_DATA_DIR}/data:/var/lib/influxdb2
    - ${APP_DATA_DIR}/config:/etc/influxdb2
