version: '3.8'
services:
  app_proxy:
    environment: 
      APP_HOST: pf-influxdb_server_1
      APP_PORT: 8086
    ports:
      - "4000:4000"
  
  server:
    image: influxdb:1.11.8@sha256:7a7c698866b3c4098f70a6f9b5e55a10ae622e9cb02eaf48cf75c2f034877a8e
    volumes:
      - ${APP_DATA_DIR}/data:/var/lib/influxdb
      - ${APP_DATA_DIR}/config:/etc/influxdb
    ports:
      - "8086:8086"


