services:
  app_proxy:
    environment:
      APP_HOST: pf-influxdb_server_1
      APP_PORT: 8086
      PROXY_AUTH_ADD: "false"
      LOG_LEVEL: info
    ports:
      - "4000:4000"
  server:
    image: influxdb:1.11.8
    container_name: pf-influxdb_server_1
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data:/var/lib/influxdb
      - ${APP_DATA_DIR}/config:/etc/influxdb
    ports:
      - "8086:8086"