version: '3.8'
services:
  app_proxy:
    environment: 
      APP_HOST: pf-influxdb_server_1
      APP_PORT: 8086
    ports:
      - "8086:8086"
  
  server:
    image: influxdb:1.11.8
    volumes:
      - ${APP_DATA_DIR}/data:/var/lib/influxdb
      - ${APP_DATA_DIR}/config:/etc/influxdb
    ports:
      - "8086:8086"


