version: "3.7"
services:
  onedrive:
    image: driveone/onedrive:edge
    container_name: onedrive
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/onedrive_conf:/onedrive/conf
      - ${UMBREL_ROOT}/home/Documents:/onedrive/data

