services:
  app_proxy:
    environment:
      APP_HOST: portalfreak-ubuntu-squid-proxy_1
      APP_PORT: 3128
      PROXY_AUTH_ADD: "false"

  server:
    image: ubuntu/squid:latest
    hostname: portalfreak-ubuntu-squid-proxy_1
    volumes:
      - ${APP_DATA_DIR}/data/logs:/var/log/squid
      - ${APP_DATA_DIR}/data:/var/spool/squid
      - ${APP_DATA_DIR}/data/config:/etc/squid/config
      - ${APP_DATA_DIR}/data/snippet:/etc/squid/conf.d/snippet.conf
    environment:
      PUID: 1000
      PGID: 1000
    restart: on-failure
