version: "3.7"

services:
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - ${APP_DATA_DIR}/data:/var/lib/influxdb
      - ${APP_DATA_DIR}/config:/etc/influxdb
