version: '3.7'

services:
  deconz:
    image: deconzcommunity/deconz
    container_name: deconz
    user: "1000:1000"
    init: true
    ports:
      - "8080:80"
      - "8443:443"
      - "5900:5900"
    VOLUMES:
      - /home/umbrel/umbrel/app-data/portalfreak-community-deconz/data/:/root/.local/share/dresden-elektronik/deCONZ
      - /home/umbrel/umbrel/app-data/portalfreak-community-deconz/opt/deCONZ/otau:/opt/deCONZ

    restart: always
    network_mode: host
    privileged: true
    environment:
      - TZ=Etc/UTC
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
