services:
  deconz:
    image: deconzcommunity/deconz
    container_name: deconz
    user: "1000:1000"
    init: true
    volumes:
      - /home/umbrel/umbrel/app-data/portalfreak-community-deconz/data/:/root/.local/share/dresden-elektronik/deCONZ
    restart: always
    network_mode: host
    privileged: true
    environment:
      - TZ=Etc/UTC
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"