services:
  app_proxy:
    environment:
      APP_HOST: pf-squid-proxy_web_1
      APP_PORT: 3128
    container_name: pf-squid-proxy_app_proxy_1

  server:
    image: ubuntu/squid:latest
    hostname: $DEVICE_DOMAIN_NAME
    restart: on-failure
    ports:
      - '3128:3128'
    volumes:
      - ${APP_DATA_DIR}/data/logs:/var/log/squid
      - ${APP_DATA_DIR}/data:/var/spool/squid
      - ${APP_DATA_DIR}/data/config:/etc/squid/config.conf
      - ${APP_DATA_DIR}/data/snippet:/etc/squid/conf.d/snippet.conf
    environment:
      PUID: 1000
      PGID: 1000
    container_name: pf-squid-proxy_server_1

  docker-host:
    image: qoomon/docker-host:3.3.1@sha256:ec9d214d7fa88932e9186ca2f4419d44661376929931248525b08e7fa9e270f7
    hostname: $DEVICE_DOMAIN_NAME
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: on-failure
    container_name: pf-squid-proxy_docker-host_1