version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: pf-squid-proxy_server_1
      APP_PORT: 3128

  server:
    image: elestio/squid:${SOFTWARE_VERSION_TAG}
    hostname: $DEVICE_DOMAIN_NAME

    volumes:
      - ${APP_DATA_DIR}/data/logs:/var/log/squid
      - ${APP_DATA_DIR}/data:/var/spool/squid
      - ${APP_DATA_DIR}/data/config:/etc/squid/config
      - ${APP_DATA_DIR}/data/snippet:/etc/squid/conf.d/snippet.conf
    restart: on-failure

