version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: pf-squid-proxy_web_1
      APP_PORT: 3128

  server:
    image: ubuntu/squid:latest
    hostname: $DEVICE_DOMAIN_NAME
    network_mode: host
    volumes:
      - ${APP_DATA_DIR}/data/logs:/var/log/squid
      - ${APP_DATA_DIR}/data:/var/spool/squid
      - ${APP_DATA_DIR}/data/config:/etc/squid/config.conf
      - ${APP_DATA_DIR}/data/snippet:/etc/squid/conf.d/snippet.conf
    environment:
      PUID: 1000
      PGID: 1000
    cap_add:
      - NET_ADMIN

    restart: on-failure